import DefaultLayout from "@/components/Layouts/DefaultLayout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My app",
  description: "Generated by franckDev21",
};

export default function DashboardLayout({children}:{children: React.ReactNode}) {
  return (
    <DefaultLayout>
      {children}
    </DefaultLayout>
  );
}
